routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/updated-activity', 'TelegramBotController@updatedActivity');

Auth::routes();

Route::get('/', function(){
    return redirect(route('login'));
})->name('home');
   
Route::group(['middleware' => ['auth']], function() {
	// Using resource helper by Laravel.
    Route::resource('roles','RoleController',['except' => ['create','show','edit']]);
    Route::resource('users','UserController',['except' => ['create','show','edit']]);
    Route::resource('hosts','HostController',['except' => ['create','show','edit']]);
    Route::resource('filters','FilterController',['except' => ['create','show','edit']]);

    // Jails URL has something different. So, i use manual url routing.
    Route::get('jails','JailController@index')->name('jails.index');
    Route::get('jails/{host}','JailController@manage')->name('jails.manage');
    Route::post('jails','JailController@store')->name('jails.store');
    Route::patch('jails/{jail}/disable','JailController@disable')->name('jails.disable');
    Route::patch('jails/{jail}/enable','JailController@enable')->name('jails.enable');
    Route::get('jails/{host}/{jail}','JailController@detail')->name('jails.detail');
    Route::patch('jails/{jail}','JailController@update')->name('jails.update');

    // Trusted Ips also using manual url routing.
    Route::post('trusted_ip/{host}/{id}','Trusted_IpController@store')->name('trusted_ips.store');
    Route::delete('trusted_ip/{host}/{jail}/{id}','Trusted_IpController@destroy')->name('trusted_ips.destroy');

    // Banned Ips also using manual url routing.
    Route::post('banned_ip/{host}/{id}','Banned_IpController@store')->name('banned_ips.store');
    Route::delete('banned_ip/{host}/{jail}/{id}','Banned_IpController@destroy')->name('banned_ips.destroy');

    // Log route only have one function, index only.
    Route::get('logs','LogController@index')->name('logs.index');

    // Dashboard route only.
    Route::get('dashboard','DashboardController@index')->name('dashboard');
});

resources/views/filter.blade.php
@extends('template')
@section('main')
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-7 align-self-center">
                        <div class="d-flex align-items-center">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb m-0 p-0">
                                    <li class="breadcrumb-item"><a href="{{ route('filters.index') }}">Filters</a>
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Notification Alerts! -->
            @if (count($errors) > 0)
              <div class="alert alert-danger mt-4">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                   @foreach ($errors->all() as $error)
                     <li>{{ $error }}</li>
                   @endforeach
                </ul>
              </div>
            @endif
            @if ($message = Session::get('success'))
                <div class="alert alert-success mt-4">
                  <p>{{ $message }}</p>
                </div>
            @endif
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- Start Location and Earnings Charts Section -->
                <!-- *************************************************************** -->
                @can('filter-create')
                <div class="row">
                    <div class="col-md-12 col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex align-items-start mb-4">
                                    <h4 class="card-title mb-0">Create Custom Filter</h4>
                                </div>
                                <div class="form-group">
                                    {!! Form::open(array('route' => 'filters.store','method'=>'POST')) !!}
                                    <label>Filter Name</label>
                                    <input type="text" name="name" class="form-control w-30" placeholder="Insert filter name here."><br>
                                    <label for="content">Content</label>
                                    <textarea class="form-control" name="content" id="content" rows="3" placeholder="Just like you write a file in filter.d" style="font-family: consolas;"></textarea><br>
                                    <button class="btn btn-success float-right" type="submit">+ Create</button>
                                    {!! Form::close() !!}
                                    <a href="https://www.regextester.com/" class="btn btn-primary float-right" target="_BLANK">Test Regex</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @endcan
                @can('filter-list')
                <h3>Available Custom Filters</h3>
                <div class="badge badge-warning badge-lg mb-3"><b>ReadMe!</b> Delete feature is still under developement.</div>
                <div class="row">
                    <div class="col-12">
                        <!-- Row -->
                        <div class="row">
                            <!-- column -->
                            @foreach($filters as $key => $filter)
                            <div class="col-lg-6 col-md-6">
                                <!-- Card -->
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="card-title"><i class="fas fa-umbrella"></i> {{ $filter->name }}<small>.conf</small></h4>
                                        {!! Form::open(['method' => 'PATCH','route' => ['filters.update', $filter->id],'style'=>'display:inline']) !!}
                                        <label for="failregex">Content</label>
                                        <textarea class="form-control mb-3" name="content" id="failregex" rows="5" placeholder="Separate regex with Enter/New line." style="font-family: consolas;">{{ $filter->content }}</textarea>
                                        @can('filter-edit')
                                            <button class="btn btn-sm btn-success" type="submit">Update</button>
                                        @endcan
                                        {!! Form::close() !!}
                                        @can('filter-delete')
                                        {!! Form::open(['method' => 'DELETE','route' => ['filters.destroy', $filter->id],'style'=>'display:inline']) !!}
                                            {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-sm']) !!}
                                        {!! Form::close() !!}
                                        @endcan
                                    </div>
                                </div>
                                <!-- Card -->
                            </div>
                            @endforeach
                        </div>
                        <!-- Row -->
                    </div>
                </div>
                <h3>Available Default Filters</h3>
                <div class="row">
                    <div class="col-12">
                        <!-- Row -->
                        <div class="row">
                            <!-- column -->
                            @foreach($filters_default as $key => $filter)
                            <div class="col-lg-3 col-md-4">
                                <!-- Card -->
                                <div class="card">
                                    <div class="card-body border-top border-right border-success rounded-top">
                                        <h4 class="card-title"><i class="fas fa-umbrella"></i> {{ $filter->name }}<small>.conf</small></h4>
                                    </div>
                                </div>
                                <!-- Card -->
                            </div>
                            @endforeach
                        </div>
                        <!-- Row -->
                    </div>
                </div>
                @endcan
                <!-- *************************************************************** -->
                <!-- End Location and Earnings Charts Section -->
                <!-- *************************************************************** -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
@stop
@section('script')
@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/host.blade.php
@extends('template')
@section('main')
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-7 align-self-center">
                        <div class="d-flex align-items-center">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb m-0 p-0">
                                    <li class="breadcrumb-item"><a href="TA-Host.html">Hosts</a>
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Notification Section -->
            @if (count($errors) > 0)
              <div class="alert alert-danger mt-4">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                   @foreach ($errors->all() as $error)
                     <li>{{ $error }}</li>
                   @endforeach
                </ul>
              </div>
            @endif
            @if ($message = Session::get('success'))
                <div class="alert alert-success mt-4">
                    <p>{{ $message }}</p>
                </div>
            @endif
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- Start Location and Earnings Charts Section -->
                <!-- *************************************************************** -->
                <div class="row">
                    @can('host-list')
                    <div class="col-md-6 col-lg-8">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex align-items-start mb-4">
                                    <h4 class="card-title mb-0">Hosts List</h4>
                                </div>
                                <div class="table-responsive">
                                <table class="table table-borderless table-hover">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Name</th>
                                            <th scope="col">IP Address</th>
                                            <th scope="col">Port</th>
                                            <th scope="col">Description</th>
                                            <th scope="col">Agent Key</th>
                                            <th scope="col">Updated At</th>
                                            <th scope="col">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($hosts as $key => $host)
                                        <tr>
                                            @can('host-edit')
                                            {!! Form::open(['method' => 'PATCH','route' => ['hosts.update', $host->id],'style'=>'display:inline']) !!}
                                            @endcan
                                            <th scope="row">{{ ++$i }}</th>
                                            <td><input type="text" class="form-control" name="name" value="{{ $host->name }}" style="min-width: 200px;"></td>
                                            <td><input type="text" class="form-control" name="ip" value="{{ $host->ip }}" style="min-width: 200px;"></td>
                                            <td><input type="number" class="form-control" name="port" value="{{ $host->port }}" style="min-width: 200px;"></td>
                                            <td><input type="text" class="form-control" name="description" value="{{ $host->description }}" style="min-width: 200px;"></td>
                                            <td><input type="text" class="form-control" name="api_key" value="{{ $host->api_key }}" style="min-width: 200px;"></td>
                                            <td>{{ $host->updated_at }}</td>
                                            <td>
                                            @can('host-edit')
                                            <button class="btn btn-sm btn-success">Update</button>
                                            {!! Form::close() !!}
                                            @endcan
                                            @can('host-delete')
                                            {!! Form::open(['method' => 'DELETE','route' => ['hosts.destroy', $host->id],'style'=>'display:inline']) !!}
                                                    {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-sm']) !!}
                                                {!! Form::close() !!}
                                            @endcan
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                    </div>
                    @endcan
                    @can('host-create')
                    <div class="col-md-6 col-lg-4">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Add Host</h4>
                                {!! Form::open(array('route' => 'hosts.store','method'=>'POST')) !!}
                                    <label>Name :</label>
                                    <input type="text" name="name" class="form-control mb-2">
                                    <label>IP :</label>
                                    <input type="text" name="ip" class="form-control mb-2">
                                    <label>Port :</label>
                                    <input type="number" name="port" class="form-control mb-2">
                                    <label>Agent Key :</label>
                                    <input type="text" name="api_key" class="form-control mb-2">
                                    <label>Description :</label>
                                    <input type="text" name="description" class="form-control mb-2">
                                    <br>
                                    <button type="submit" class="btn btn-success">+ Add</button>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                    @endcan
                </div>
                <!-- *************************************************************** -->
                <!-- End Location and Earnings Charts Section -->
                <!-- *************************************************************** -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
@stop
@section('script')
@stop

resources/views/user.blade.php
@extends('template')
@section('main')
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-7 align-self-center">
                        <div class="d-flex align-items-center">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb m-0 p-0">
                                    <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Users</a>
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Alert BOX -->
            @if (count($errors) > 0)
              <div class="alert alert-danger mt-4">
                <strong>Whoops!</strong> Something errors with your input.<br><br>
                <ul>
                   @foreach ($errors->all() as $error)
                     <li>{{ $error }}</li>
                   @endforeach
                </ul>
              </div>
            @endif
            @if ($message = Session::get('success'))
                <div class="alert alert-success mt-4">
                  <p>{{ $message }}</p>
                </div>
            @endif
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- Start Location and Earnings Charts Section -->
                <!-- *************************************************************** -->
                <div class="row">
                    @can('user-list')
                    <div class="col-md-6 col-lg-8">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex align-items-start mb-4">
                                    <h4 class="card-title mb-0">User List</h4>
                                </div>
                                <div class="table-responsive">
                                <table class="table table-borderless table-hover">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Full name</th>
                                            <th scope="col">Email</th>
                                            <th scope="col">Password</th>
                                            <th scope="col">Last updated</th>
                                            <th scope="col">Role</th>
                                            <th scope="col">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         @foreach ($data as $key => $user)
                                        <tr>
                                         {!! Form::open(['method' => 'PATCH','route' => ['users.update', $user->id],'style'=>'display:inline']) !!}
                                            <th scope="row">{{ ++$i }}</th>
                                            <td><input type="text" class="form-control" name="full_name" value="{{ $user->full_name }}" style="min-width: 200px;"></td>
                                            <td><input type="email" class="form-control" name="email" value="{{ $user->email }}" style="min-width: 200px;"></td>
                                            <td><input type="password" class="form-control" name="password"  autocomplete="off" placeholder="Kata sandi baru" style="min-width: 200px;">
                                            <td>{{ $user->updated_at }}</td>
                                            <td>
                                                @if($user->getRoleNames()=="[]")
                                                    <select class="form-control" style="min-width: 100px;" name="role">
                                                           <option>No role</option>
                                                           @foreach($role as $key => $rolet)
                                                            <option>{{ $rolet->name }}</option>
                                                           @endforeach
                                                    </select>
                                                @else
                                                    @foreach($user->getRoleNames() as $v)
                                                       <select class="form-control" style="min-width: 100px;" name="role">
                                                           <option selected="">{{ $v }}</option>
                                                           @foreach($role as $key => $rolet)
                                                           @if($rolet->name !== $v)
                                                            <option>{{ $rolet->name }}</option>
                                                            @endif
                                                           @endforeach
                                                       </select>
                                                    @endforeach
                                                
                                                @endif
                                            </td>
                                            <td>
                                                @can('user-edit')
                                                <button class="btn btn-sm btn-success" type="submit">Update</button>
                                                @endcan
                                                </form>
                                                {!! Form::close() !!}
                                                @can('user-delete')
                                                {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $user->id],'style'=>'display:inline']) !!}
                                                    {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-sm']) !!}
                                                {!! Form::close() !!}
                                                @endcan
                                            </td>
                                        </tr>
                                         @endforeach
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                    </div>
                    @endcan
                    @can('user-create')
                    <div class="col-md-6 col-lg-4">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Add User</h4>
                                {!! Form::open(array('route' => 'users.store','method'=>'POST')) !!}
                                    <label>Full Name:</label>
                                    <input type="text" name="full_name" class="form-control mb-2">
                                    <label>Email :</label>
                                    <input type="email" name="email" class="form-control mb-2" autocomplete="off">
                                    <label>Password:</label>
                                    <input type="password" name="password" class="form-control mb-2" autocomplete="off">
                                    <label>Confirm Password :</label>
                                    <input type="password" name="confirm-password" class="form-control mb-2" autocomplete="off">
                                    <label>Role :</label>
                                    {!! Form::select('roles[]', $roles,[], array('class' => 'form-control')) !!}
                                    <br>
                                    <button type="submit" class="btn btn-success">+ Add</button>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                    @endcan
                </div>
                <!-- *************************************************************** -->
                <!-- End Location and Earnings Charts Section -->
                <!-- *************************************************************** -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
@stop
@section('script')
@stop